// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "github.com/tphakala/birdnet-go/internal/datastore/v2/entities"

	repository "github.com/tphakala/birdnet-go/internal/datastore/v2/repository"

	time "time"
)

// MockAlertRuleRepository is an autogenerated mock type for the AlertRuleRepository type
type MockAlertRuleRepository struct {
	mock.Mock
}

type MockAlertRuleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlertRuleRepository) EXPECT() *MockAlertRuleRepository_Expecter {
	return &MockAlertRuleRepository_Expecter{mock: &_m.Mock}
}

// CountRulesByName provides a mock function with given fields: ctx, name
func (_m *MockAlertRuleRepository) CountRulesByName(ctx context.Context, name string) (int64, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CountRulesByName")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRuleRepository_CountRulesByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountRulesByName'
type MockAlertRuleRepository_CountRulesByName_Call struct {
	*mock.Call
}

// CountRulesByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockAlertRuleRepository_Expecter) CountRulesByName(ctx interface{}, name interface{}) *MockAlertRuleRepository_CountRulesByName_Call {
	return &MockAlertRuleRepository_CountRulesByName_Call{Call: _e.mock.On("CountRulesByName", ctx, name)}
}

func (_c *MockAlertRuleRepository_CountRulesByName_Call) Run(run func(ctx context.Context, name string)) *MockAlertRuleRepository_CountRulesByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAlertRuleRepository_CountRulesByName_Call) Return(_a0 int64, _a1 error) *MockAlertRuleRepository_CountRulesByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRuleRepository_CountRulesByName_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockAlertRuleRepository_CountRulesByName_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRule provides a mock function with given fields: ctx, rule
func (_m *MockAlertRuleRepository) CreateRule(ctx context.Context, rule *entities.AlertRule) error {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for CreateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.AlertRule) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertRuleRepository_CreateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRule'
type MockAlertRuleRepository_CreateRule_Call struct {
	*mock.Call
}

// CreateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *entities.AlertRule
func (_e *MockAlertRuleRepository_Expecter) CreateRule(ctx interface{}, rule interface{}) *MockAlertRuleRepository_CreateRule_Call {
	return &MockAlertRuleRepository_CreateRule_Call{Call: _e.mock.On("CreateRule", ctx, rule)}
}

func (_c *MockAlertRuleRepository_CreateRule_Call) Run(run func(ctx context.Context, rule *entities.AlertRule)) *MockAlertRuleRepository_CreateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.AlertRule))
	})
	return _c
}

func (_c *MockAlertRuleRepository_CreateRule_Call) Return(_a0 error) *MockAlertRuleRepository_CreateRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertRuleRepository_CreateRule_Call) RunAndReturn(run func(context.Context, *entities.AlertRule) error) *MockAlertRuleRepository_CreateRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBuiltInRules provides a mock function with given fields: ctx
func (_m *MockAlertRuleRepository) DeleteBuiltInRules(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBuiltInRules")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRuleRepository_DeleteBuiltInRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBuiltInRules'
type MockAlertRuleRepository_DeleteBuiltInRules_Call struct {
	*mock.Call
}

// DeleteBuiltInRules is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAlertRuleRepository_Expecter) DeleteBuiltInRules(ctx interface{}) *MockAlertRuleRepository_DeleteBuiltInRules_Call {
	return &MockAlertRuleRepository_DeleteBuiltInRules_Call{Call: _e.mock.On("DeleteBuiltInRules", ctx)}
}

func (_c *MockAlertRuleRepository_DeleteBuiltInRules_Call) Run(run func(ctx context.Context)) *MockAlertRuleRepository_DeleteBuiltInRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAlertRuleRepository_DeleteBuiltInRules_Call) Return(_a0 int64, _a1 error) *MockAlertRuleRepository_DeleteBuiltInRules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRuleRepository_DeleteBuiltInRules_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockAlertRuleRepository_DeleteBuiltInRules_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteHistory provides a mock function with given fields: ctx
func (_m *MockAlertRuleRepository) DeleteHistory(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteHistory")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRuleRepository_DeleteHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteHistory'
type MockAlertRuleRepository_DeleteHistory_Call struct {
	*mock.Call
}

// DeleteHistory is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAlertRuleRepository_Expecter) DeleteHistory(ctx interface{}) *MockAlertRuleRepository_DeleteHistory_Call {
	return &MockAlertRuleRepository_DeleteHistory_Call{Call: _e.mock.On("DeleteHistory", ctx)}
}

func (_c *MockAlertRuleRepository_DeleteHistory_Call) Run(run func(ctx context.Context)) *MockAlertRuleRepository_DeleteHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAlertRuleRepository_DeleteHistory_Call) Return(_a0 int64, _a1 error) *MockAlertRuleRepository_DeleteHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRuleRepository_DeleteHistory_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockAlertRuleRepository_DeleteHistory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteHistoryBefore provides a mock function with given fields: ctx, before
func (_m *MockAlertRuleRepository) DeleteHistoryBefore(ctx context.Context, before time.Time) (int64, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for DeleteHistoryBefore")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, before)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRuleRepository_DeleteHistoryBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteHistoryBefore'
type MockAlertRuleRepository_DeleteHistoryBefore_Call struct {
	*mock.Call
}

// DeleteHistoryBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *MockAlertRuleRepository_Expecter) DeleteHistoryBefore(ctx interface{}, before interface{}) *MockAlertRuleRepository_DeleteHistoryBefore_Call {
	return &MockAlertRuleRepository_DeleteHistoryBefore_Call{Call: _e.mock.On("DeleteHistoryBefore", ctx, before)}
}

func (_c *MockAlertRuleRepository_DeleteHistoryBefore_Call) Run(run func(ctx context.Context, before time.Time)) *MockAlertRuleRepository_DeleteHistoryBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockAlertRuleRepository_DeleteHistoryBefore_Call) Return(_a0 int64, _a1 error) *MockAlertRuleRepository_DeleteHistoryBefore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRuleRepository_DeleteHistoryBefore_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *MockAlertRuleRepository_DeleteHistoryBefore_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRule provides a mock function with given fields: ctx, id
func (_m *MockAlertRuleRepository) DeleteRule(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertRuleRepository_DeleteRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRule'
type MockAlertRuleRepository_DeleteRule_Call struct {
	*mock.Call
}

// DeleteRule is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockAlertRuleRepository_Expecter) DeleteRule(ctx interface{}, id interface{}) *MockAlertRuleRepository_DeleteRule_Call {
	return &MockAlertRuleRepository_DeleteRule_Call{Call: _e.mock.On("DeleteRule", ctx, id)}
}

func (_c *MockAlertRuleRepository_DeleteRule_Call) Run(run func(ctx context.Context, id uint)) *MockAlertRuleRepository_DeleteRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAlertRuleRepository_DeleteRule_Call) Return(_a0 error) *MockAlertRuleRepository_DeleteRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertRuleRepository_DeleteRule_Call) RunAndReturn(run func(context.Context, uint) error) *MockAlertRuleRepository_DeleteRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnabledRules provides a mock function with given fields: ctx
func (_m *MockAlertRuleRepository) GetEnabledRules(ctx context.Context) ([]entities.AlertRule, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetEnabledRules")
	}

	var r0 []entities.AlertRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.AlertRule, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.AlertRule); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.AlertRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRuleRepository_GetEnabledRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnabledRules'
type MockAlertRuleRepository_GetEnabledRules_Call struct {
	*mock.Call
}

// GetEnabledRules is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAlertRuleRepository_Expecter) GetEnabledRules(ctx interface{}) *MockAlertRuleRepository_GetEnabledRules_Call {
	return &MockAlertRuleRepository_GetEnabledRules_Call{Call: _e.mock.On("GetEnabledRules", ctx)}
}

func (_c *MockAlertRuleRepository_GetEnabledRules_Call) Run(run func(ctx context.Context)) *MockAlertRuleRepository_GetEnabledRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAlertRuleRepository_GetEnabledRules_Call) Return(_a0 []entities.AlertRule, _a1 error) *MockAlertRuleRepository_GetEnabledRules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRuleRepository_GetEnabledRules_Call) RunAndReturn(run func(context.Context) ([]entities.AlertRule, error)) *MockAlertRuleRepository_GetEnabledRules_Call {
	_c.Call.Return(run)
	return _c
}

// GetRule provides a mock function with given fields: ctx, id
func (_m *MockAlertRuleRepository) GetRule(ctx context.Context, id uint) (*entities.AlertRule, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRule")
	}

	var r0 *entities.AlertRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.AlertRule, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.AlertRule); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AlertRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRuleRepository_GetRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRule'
type MockAlertRuleRepository_GetRule_Call struct {
	*mock.Call
}

// GetRule is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockAlertRuleRepository_Expecter) GetRule(ctx interface{}, id interface{}) *MockAlertRuleRepository_GetRule_Call {
	return &MockAlertRuleRepository_GetRule_Call{Call: _e.mock.On("GetRule", ctx, id)}
}

func (_c *MockAlertRuleRepository_GetRule_Call) Run(run func(ctx context.Context, id uint)) *MockAlertRuleRepository_GetRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAlertRuleRepository_GetRule_Call) Return(_a0 *entities.AlertRule, _a1 error) *MockAlertRuleRepository_GetRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRuleRepository_GetRule_Call) RunAndReturn(run func(context.Context, uint) (*entities.AlertRule, error)) *MockAlertRuleRepository_GetRule_Call {
	_c.Call.Return(run)
	return _c
}

// ListHistory provides a mock function with given fields: ctx, filter
func (_m *MockAlertRuleRepository) ListHistory(ctx context.Context, filter repository.AlertHistoryFilter) ([]entities.AlertHistory, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListHistory")
	}

	var r0 []entities.AlertHistory
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AlertHistoryFilter) ([]entities.AlertHistory, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.AlertHistoryFilter) []entities.AlertHistory); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.AlertHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.AlertHistoryFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.AlertHistoryFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAlertRuleRepository_ListHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHistory'
type MockAlertRuleRepository_ListHistory_Call struct {
	*mock.Call
}

// ListHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.AlertHistoryFilter
func (_e *MockAlertRuleRepository_Expecter) ListHistory(ctx interface{}, filter interface{}) *MockAlertRuleRepository_ListHistory_Call {
	return &MockAlertRuleRepository_ListHistory_Call{Call: _e.mock.On("ListHistory", ctx, filter)}
}

func (_c *MockAlertRuleRepository_ListHistory_Call) Run(run func(ctx context.Context, filter repository.AlertHistoryFilter)) *MockAlertRuleRepository_ListHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.AlertHistoryFilter))
	})
	return _c
}

func (_c *MockAlertRuleRepository_ListHistory_Call) Return(_a0 []entities.AlertHistory, _a1 int64, _a2 error) *MockAlertRuleRepository_ListHistory_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAlertRuleRepository_ListHistory_Call) RunAndReturn(run func(context.Context, repository.AlertHistoryFilter) ([]entities.AlertHistory, int64, error)) *MockAlertRuleRepository_ListHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListRules provides a mock function with given fields: ctx, filter
func (_m *MockAlertRuleRepository) ListRules(ctx context.Context, filter repository.AlertRuleFilter) ([]entities.AlertRule, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListRules")
	}

	var r0 []entities.AlertRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AlertRuleFilter) ([]entities.AlertRule, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.AlertRuleFilter) []entities.AlertRule); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.AlertRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.AlertRuleFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRuleRepository_ListRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRules'
type MockAlertRuleRepository_ListRules_Call struct {
	*mock.Call
}

// ListRules is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.AlertRuleFilter
func (_e *MockAlertRuleRepository_Expecter) ListRules(ctx interface{}, filter interface{}) *MockAlertRuleRepository_ListRules_Call {
	return &MockAlertRuleRepository_ListRules_Call{Call: _e.mock.On("ListRules", ctx, filter)}
}

func (_c *MockAlertRuleRepository_ListRules_Call) Run(run func(ctx context.Context, filter repository.AlertRuleFilter)) *MockAlertRuleRepository_ListRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.AlertRuleFilter))
	})
	return _c
}

func (_c *MockAlertRuleRepository_ListRules_Call) Return(_a0 []entities.AlertRule, _a1 error) *MockAlertRuleRepository_ListRules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRuleRepository_ListRules_Call) RunAndReturn(run func(context.Context, repository.AlertRuleFilter) ([]entities.AlertRule, error)) *MockAlertRuleRepository_ListRules_Call {
	_c.Call.Return(run)
	return _c
}

// SaveHistory provides a mock function with given fields: ctx, history
func (_m *MockAlertRuleRepository) SaveHistory(ctx context.Context, history *entities.AlertHistory) error {
	ret := _m.Called(ctx, history)

	if len(ret) == 0 {
		panic("no return value specified for SaveHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.AlertHistory) error); ok {
		r0 = rf(ctx, history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertRuleRepository_SaveHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveHistory'
type MockAlertRuleRepository_SaveHistory_Call struct {
	*mock.Call
}

// SaveHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - history *entities.AlertHistory
func (_e *MockAlertRuleRepository_Expecter) SaveHistory(ctx interface{}, history interface{}) *MockAlertRuleRepository_SaveHistory_Call {
	return &MockAlertRuleRepository_SaveHistory_Call{Call: _e.mock.On("SaveHistory", ctx, history)}
}

func (_c *MockAlertRuleRepository_SaveHistory_Call) Run(run func(ctx context.Context, history *entities.AlertHistory)) *MockAlertRuleRepository_SaveHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.AlertHistory))
	})
	return _c
}

func (_c *MockAlertRuleRepository_SaveHistory_Call) Return(_a0 error) *MockAlertRuleRepository_SaveHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertRuleRepository_SaveHistory_Call) RunAndReturn(run func(context.Context, *entities.AlertHistory) error) *MockAlertRuleRepository_SaveHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleRule provides a mock function with given fields: ctx, id, enabled
func (_m *MockAlertRuleRepository) ToggleRule(ctx context.Context, id uint, enabled bool) error {
	ret := _m.Called(ctx, id, enabled)

	if len(ret) == 0 {
		panic("no return value specified for ToggleRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, bool) error); ok {
		r0 = rf(ctx, id, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertRuleRepository_ToggleRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleRule'
type MockAlertRuleRepository_ToggleRule_Call struct {
	*mock.Call
}

// ToggleRule is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - enabled bool
func (_e *MockAlertRuleRepository_Expecter) ToggleRule(ctx interface{}, id interface{}, enabled interface{}) *MockAlertRuleRepository_ToggleRule_Call {
	return &MockAlertRuleRepository_ToggleRule_Call{Call: _e.mock.On("ToggleRule", ctx, id, enabled)}
}

func (_c *MockAlertRuleRepository_ToggleRule_Call) Run(run func(ctx context.Context, id uint, enabled bool)) *MockAlertRuleRepository_ToggleRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(bool))
	})
	return _c
}

func (_c *MockAlertRuleRepository_ToggleRule_Call) Return(_a0 error) *MockAlertRuleRepository_ToggleRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertRuleRepository_ToggleRule_Call) RunAndReturn(run func(context.Context, uint, bool) error) *MockAlertRuleRepository_ToggleRule_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRule provides a mock function with given fields: ctx, rule
func (_m *MockAlertRuleRepository) UpdateRule(ctx context.Context, rule *entities.AlertRule) error {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.AlertRule) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlertRuleRepository_UpdateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRule'
type MockAlertRuleRepository_UpdateRule_Call struct {
	*mock.Call
}

// UpdateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *entities.AlertRule
func (_e *MockAlertRuleRepository_Expecter) UpdateRule(ctx interface{}, rule interface{}) *MockAlertRuleRepository_UpdateRule_Call {
	return &MockAlertRuleRepository_UpdateRule_Call{Call: _e.mock.On("UpdateRule", ctx, rule)}
}

func (_c *MockAlertRuleRepository_UpdateRule_Call) Run(run func(ctx context.Context, rule *entities.AlertRule)) *MockAlertRuleRepository_UpdateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.AlertRule))
	})
	return _c
}

func (_c *MockAlertRuleRepository_UpdateRule_Call) Return(_a0 error) *MockAlertRuleRepository_UpdateRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlertRuleRepository_UpdateRule_Call) RunAndReturn(run func(context.Context, *entities.AlertRule) error) *MockAlertRuleRepository_UpdateRule_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlertRuleRepository creates a new instance of MockAlertRuleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlertRuleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlertRuleRepository {
	mock := &MockAlertRuleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
