# Root directory
root = "."
tmp_dir = "tmp"

# Build configuration
[build]
  cmd = """
    export CGO_ENABLED=1
    export CGO_CFLAGS="-I${HOME}/src/tensorflow"
    export CGO_LDFLAGS="-L/usr/lib -ltensorflowlite_c"
    go build -v -x -ldflags "-s -w -X main.buildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)" -o ./tmp/main .
  """
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "css"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

  # Tailwind CSS rebuild
  [build.tailwind]
    cmd = "tailwindcss -i input.css -o assets/tailwind.css"
    path = "input.css"
    
[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true