version: "2"
output:
  sort-order:
    - linter
    - severity
    - file
linters:
  enable:
    # Existing linters
    - copyloopvar
    - durationcheck
    - errname
    - errorlint
    - gocognit
    - gocritic
    - misspell
    - predeclared
    - revive
    - unconvert
    - wastedassign
    # Security & quality linters
    - gosec
    - goconst
    - staticcheck
    - ineffassign
    - bodyclose
    - fatcontext
    - iface
    - dupl
    #- ireturn
    - nilnil
    - nilerr
    - thelper
    - testifylint
    - gocyclo
    - modernize
    - forbidigo  # Sensitive field name detection
    # Performance linters
    - prealloc
    - exhaustive
  disable:
    - unused
  settings:
    gocognit:
      min-complexity: 50
    gocritic:
      disabled-checks:
        - commentFormatting
        - commentedOutCode
      enabled-tags:
        - style
        - diagnostic
        - performance
      settings:
        ruleguard:
          rules: "rules/waitgroup.go"
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    gosec:
      # Configure gosec for security scanning
      excludes:
        - G104  # Audit errors not checked (covered by errcheck)
      severity: medium
      confidence: medium
    prealloc:
      # Configure prealloc for slice optimization
      simple: true
      range-loops: true
      for-loops: true
    exhaustive:
      # Check exhaustiveness of enum switch statements
      default-signifies-exhaustive: true
    forbidigo:
      # Detect potential sensitive data logging
      # Use logger.Username(), logger.Password(), logger.Token(), etc. instead
      forbid:
        # Password/credential field names - always use logger.Password() or logger.Credential()
        # Uses .* to catch variations like "user_password", "mqtt_secret", etc.
        - pattern: 'logger\.String\(\s*"(?i)[^"]*(password|passwd|pwd|secret|credential)[^"]*"'
          msg: "Use logger.Password() or logger.Credential() for sensitive credential fields instead of logger.String()"
        # Token field names - always use logger.Token()
        - pattern: 'logger\.String\(\s*"(?i)[^"]*(token|bearer|api_key|apikey|auth_token|access_token)[^"]*"'
          msg: "Use logger.Token() for token fields instead of logger.String()"
        # Username field names - always use logger.Username()
        - pattern: 'logger\.String\(\s*"(?i)[^"]*(username|user_name|userid|user_id|login)[^"]*"'
          msg: "Use logger.Username() for username fields instead of logger.String()"
        # Email addresses - should be sanitized
        - pattern: 'logger\.String\(\s*"(?i)[^"]*(email|e-mail|mail)[^"]*"'
          msg: "Use logger.SanitizedString() for email fields to redact sensitive data"
      analyze-types: false
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
