---
run:
  timeout: 5m
  concurrency: 0

output:
  sort-results: true
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  show-stats: true
  sort-order:
    - linter
    - severity
    - file

linters:
  enable:
    - durationcheck
    - errname
    - errorlint
    - exportloopref
    #- gocognit
    #- gocritic
    - gofmt
    #- gofumpt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - nolintlint
    - predeclared
    #- revive
    - staticcheck
    - unconvert
    #- unused
    - wastedassign
  disable:
    - unused

linters-settings:
  gocognit:
    min-complexity: 50
  gocritic:
    disabled-checks:
      - commentFormatting
    enabled-tags:
      - style 
      - diagnostic
      - performance

issues:
  max-same-issues: 0
  new: false
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
        - govet
        - structcheck
    - path: internal/birdnet
      linters:
        - typecheck
  exclude-files:
    # Skip autogenerated files.
    - ^.*\.(pb|y)\.go$

