/**
 * useSpeciesHistory.svelte.ts
 *
 * Loads species-level history for the detection detail page's History tab:
 * first/last heard, lifetime detection count, a zero-filled daily count series
 * for the 30 days ending on the viewed detection's date, and the most recent
 * other detections of the same species.
 *
 * All three requests run in parallel. Results are cached per
 * (scientificName, anchorDate) so switching tabs back and forth does not refetch.
 *
 * Usage:
 *   const history = useSpeciesHistory();
 *   await history.load(detection.scientificName, detection.date, detection.id);
 */

import { api } from '$lib/utils/api';
import { addDays } from '$lib/utils/date';
import { t } from '$lib/i18n';
import { loggers } from '$lib/utils/logger';

const logger = loggers.ui;

/** Days shown in the daily-count series, inclusive of the anchor date. */
export const HISTORY_WINDOW_DAYS = 30;

/** Most recent other detections listed in the tab. */
export const RECENT_LIMIT = 10;

export interface SpeciesHistoryEntry {
  /** Numeric, as the API sends it (`ID uint` in the detections response). */
  id: number;
  timestamp: string;
  confidence: number;
}

export interface SpeciesHistory {
  /** ISO timestamp of the earliest detection of this species, or null if none. */
  firstHeard: string | null;
  /** ISO timestamp of the most recent detection of this species, or null if none. */
  lastHeard: string | null;
  /** Lifetime count for this species, from the unfiltered search total. */
  totalDetections: number;
  /** One count per day, ascending, length HISTORY_WINDOW_DAYS, zero-filled. */
  dailyCounts: number[];
  /** Last day covered by dailyCounts (YYYY-MM-DD) — the anchor date. */
  windowEnd: string;
  /** Most recent other detections, excluding the one being viewed. */
  recent: SpeciesHistoryEntry[];
}

/** Shape of the POST /api/v2/search response fields this composable reads. */
interface SearchResponse {
  results?: SpeciesHistoryEntry[];
  total?: number;
}

/** Shape of the GET /api/v2/analytics/time/daily response. */
interface DailyResponse {
  data?: { date: string; count: number }[];
}

function searchBody(scientificName: string, sortBy: 'date_desc' | 'date_asc') {
  return {
    species: '',
    speciesScientific: [scientificName],
    page: 1,
    sortBy,
  };
}

/**
 * Expand a sparse daily series into one ascending slot per day.
 *
 * The API omits days with no detections, so consuming `data` directly would
 * close up quiet stretches. Row order is deliberately not relied on: the rows
 * are indexed by date into a Map and the output is then generated by walking
 * the window from oldest to newest, so any input order yields the same chart.
 * (The two datastore backends genuinely disagree — the legacy store orders by
 * date ascending, the v2 store by date descending.)
 */
function buildDailyCounts(rows: { date: string; count: number }[], windowEnd: string): number[] {
  const byDate = new Map<string, number>();
  for (const row of rows) {
    byDate.set(row.date, row.count);
  }

  const counts: number[] = [];
  for (let offset = HISTORY_WINDOW_DAYS - 1; offset >= 0; offset--) {
    const day = addDays(windowEnd, -offset);
    counts.push(byDate.get(day) ?? 0);
  }
  return counts;
}

export function useSpeciesHistory() {
  let data = $state<SpeciesHistory | null>(null);
  let isLoading = $state(false);
  let error = $state<string | null>(null);

  /** Identifies what `data` holds, so a repeat activation is a no-op. */
  let loadedKey: string | null = null;
  let controller: AbortController | null = null;

  async function load(
    scientificName: string,
    anchorDate: string,
    currentDetectionId: number
  ): Promise<void> {
    const name = scientificName.trim();
    if (name === '' || anchorDate === '') return;

    const key = `${name}|${anchorDate}`;
    if (key === loadedKey && data !== null) return;

    controller?.abort();
    const active = new AbortController();
    controller = active;
    const { signal } = active;

    isLoading = true;
    error = null;

    try {
      // Inside the try on purpose: addDays throws on an unparseable anchor date
      // (e.g. a legacy "0000-00-00" row). Outside it, the throw would skip the
      // finally and pin the tab to a loading state that never resolves.
      const windowStart = addDays(anchorDate, -(HISTORY_WINDOW_DAYS - 1));
      const dailyUrl =
        `/api/v2/analytics/time/daily?start_date=${encodeURIComponent(windowStart)}` +
        `&end_date=${encodeURIComponent(anchorDate)}&species=${encodeURIComponent(name)}`;

      const [newest, oldest, daily] = await Promise.all([
        api.post<SearchResponse>('/api/v2/search', searchBody(name, 'date_desc'), { signal }),
        api.post<SearchResponse>('/api/v2/search', searchBody(name, 'date_asc'), { signal }),
        api.get<DailyResponse>(dailyUrl, { signal }),
      ]);

      // Guard the captured signal, not `controller`, which may already point at
      // a newer load by the time this resolves.
      if (signal.aborted) return;

      const newestRows = newest.results ?? [];
      const oldestRows = oldest.results ?? [];

      data = {
        firstHeard: oldestRows[0]?.timestamp ?? null,
        lastHeard: newestRows[0]?.timestamp ?? null,
        totalDetections: newest.total ?? 0,
        dailyCounts: buildDailyCounts(daily.data ?? [], anchorDate),
        windowEnd: anchorDate,
        recent: newestRows.filter(r => r.id !== currentDetectionId).slice(0, RECENT_LIMIT),
      };
      loadedKey = key;
    } catch (err) {
      if (signal.aborted || (err instanceof Error && err.name === 'AbortError')) return;
      logger.error('Failed to load species history:', err);
      error = t('detections.history.loadError');
      data = null;
      loadedKey = null;
    } finally {
      if (controller === active) {
        controller = null;
        isLoading = false;
      }
    }
  }

  function reset(): void {
    controller?.abort();
    controller = null;
    data = null;
    error = null;
    isLoading = false;
    loadedKey = null;
  }

  return {
    get data() {
      return data;
    },
    get isLoading() {
      return isLoading;
    },
    get error() {
      return error;
    },
    load,
    reset,
  };
}
