// Code generated by "stringer -type=AuthMethod"; DO NOT EDIT.

package auth

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthMethodUnknown-0]
	_ = x[AuthMethodToken-1]
	_ = x[AuthMethodSession-2]
	_ = x[AuthMethodSubnet-3]
	_ = x[AuthMethodNone-4]
}

const _AuthMethod_name = "AuthMethodUnknownAuthMethodTokenAuthMethodSessionAuthMethodSubnetAuthMethodNone"

var _AuthMethod_index = [...]uint8{0, 17, 32, 49, 65, 79}

func (i AuthMethod) String() string {
	if i >= AuthMethod(len(_AuthMethod_index)-1) {
		return "AuthMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthMethod_name[_AuthMethod_index[i]:_AuthMethod_index[i+1]]
}
