// Code generated by "stringer -type=AuthMethod"; DO NOT EDIT.

package auth

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthMethodUnknown-0]
	_ = x[AuthMethodBasicAuth-1]
	_ = x[AuthMethodToken-2]
	_ = x[AuthMethodOAuth2-3]
	_ = x[AuthMethodBrowserSession-4]
	_ = x[AuthMethodAPIKey-5]
}

const _AuthMethod_name = "AuthMethodUnknownAuthMethodBasicAuthAuthMethodTokenAuthMethodOAuth2AuthMethodBrowserSessionAuthMethodAPIKey"

var _AuthMethod_index = [...]uint8{0, 17, 36, 51, 67, 91, 107}

func (i AuthMethod) String() string {
	if i < 0 || i >= AuthMethod(len(_AuthMethod_index)-1) {
		return "AuthMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthMethod_name[_AuthMethod_index[i]:_AuthMethod_index[i+1]]
}
