// Code generated by "stringer -type=AuthMethod -trimprefix=AuthMethod"; DO NOT EDIT.

package auth

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthMethodUnknown-0]
	_ = x[AuthMethodNone-1]
	_ = x[AuthMethodBasicAuth-2]
	_ = x[AuthMethodToken-3]
	_ = x[AuthMethodOAuth2-4]
	_ = x[AuthMethodBrowserSession-5]
	_ = x[AuthMethodAPIKey-6]
}

const _AuthMethod_name = "UnknownNoneBasicAuthTokenOAuth2BrowserSessionAPIKey"

var _AuthMethod_index = [...]uint8{0, 7, 11, 20, 25, 31, 45, 51}

func (i AuthMethod) String() string {
	if i < 0 || i >= AuthMethod(len(_AuthMethod_index)-1) {
		return "AuthMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthMethod_name[_AuthMethod_index[i]:_AuthMethod_index[i+1]]
}
