// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockErrorEvent is an autogenerated mock type for the ErrorEvent type
type MockErrorEvent struct {
	mock.Mock
}

type MockErrorEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorEvent) EXPECT() *MockErrorEvent_Expecter {
	return &MockErrorEvent_Expecter{mock: &_m.Mock}
}

// GetCategory provides a mock function with no fields
func (_m *MockErrorEvent) GetCategory() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCategory")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockErrorEvent_GetCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategory'
type MockErrorEvent_GetCategory_Call struct {
	*mock.Call
}

// GetCategory is a helper method to define mock.On call
func (_e *MockErrorEvent_Expecter) GetCategory() *MockErrorEvent_GetCategory_Call {
	return &MockErrorEvent_GetCategory_Call{Call: _e.mock.On("GetCategory")}
}

func (_c *MockErrorEvent_GetCategory_Call) Run(run func()) *MockErrorEvent_GetCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockErrorEvent_GetCategory_Call) Return(_a0 string) *MockErrorEvent_GetCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockErrorEvent_GetCategory_Call) RunAndReturn(run func() string) *MockErrorEvent_GetCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponent provides a mock function with no fields
func (_m *MockErrorEvent) GetComponent() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetComponent")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockErrorEvent_GetComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponent'
type MockErrorEvent_GetComponent_Call struct {
	*mock.Call
}

// GetComponent is a helper method to define mock.On call
func (_e *MockErrorEvent_Expecter) GetComponent() *MockErrorEvent_GetComponent_Call {
	return &MockErrorEvent_GetComponent_Call{Call: _e.mock.On("GetComponent")}
}

func (_c *MockErrorEvent_GetComponent_Call) Run(run func()) *MockErrorEvent_GetComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockErrorEvent_GetComponent_Call) Return(_a0 string) *MockErrorEvent_GetComponent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockErrorEvent_GetComponent_Call) RunAndReturn(run func() string) *MockErrorEvent_GetComponent_Call {
	_c.Call.Return(run)
	return _c
}

// GetContext provides a mock function with no fields
func (_m *MockErrorEvent) GetContext() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// MockErrorEvent_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type MockErrorEvent_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
func (_e *MockErrorEvent_Expecter) GetContext() *MockErrorEvent_GetContext_Call {
	return &MockErrorEvent_GetContext_Call{Call: _e.mock.On("GetContext")}
}

func (_c *MockErrorEvent_GetContext_Call) Run(run func()) *MockErrorEvent_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockErrorEvent_GetContext_Call) Return(_a0 map[string]interface{}) *MockErrorEvent_GetContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockErrorEvent_GetContext_Call) RunAndReturn(run func() map[string]interface{}) *MockErrorEvent_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetError provides a mock function with no fields
func (_m *MockErrorEvent) GetError() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockErrorEvent_GetError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetError'
type MockErrorEvent_GetError_Call struct {
	*mock.Call
}

// GetError is a helper method to define mock.On call
func (_e *MockErrorEvent_Expecter) GetError() *MockErrorEvent_GetError_Call {
	return &MockErrorEvent_GetError_Call{Call: _e.mock.On("GetError")}
}

func (_c *MockErrorEvent_GetError_Call) Run(run func()) *MockErrorEvent_GetError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockErrorEvent_GetError_Call) Return(_a0 error) *MockErrorEvent_GetError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockErrorEvent_GetError_Call) RunAndReturn(run func() error) *MockErrorEvent_GetError_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessage provides a mock function with no fields
func (_m *MockErrorEvent) GetMessage() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMessage")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockErrorEvent_GetMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessage'
type MockErrorEvent_GetMessage_Call struct {
	*mock.Call
}

// GetMessage is a helper method to define mock.On call
func (_e *MockErrorEvent_Expecter) GetMessage() *MockErrorEvent_GetMessage_Call {
	return &MockErrorEvent_GetMessage_Call{Call: _e.mock.On("GetMessage")}
}

func (_c *MockErrorEvent_GetMessage_Call) Run(run func()) *MockErrorEvent_GetMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockErrorEvent_GetMessage_Call) Return(_a0 string) *MockErrorEvent_GetMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockErrorEvent_GetMessage_Call) RunAndReturn(run func() string) *MockErrorEvent_GetMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimestamp provides a mock function with no fields
func (_m *MockErrorEvent) GetTimestamp() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTimestamp")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockErrorEvent_GetTimestamp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimestamp'
type MockErrorEvent_GetTimestamp_Call struct {
	*mock.Call
}

// GetTimestamp is a helper method to define mock.On call
func (_e *MockErrorEvent_Expecter) GetTimestamp() *MockErrorEvent_GetTimestamp_Call {
	return &MockErrorEvent_GetTimestamp_Call{Call: _e.mock.On("GetTimestamp")}
}

func (_c *MockErrorEvent_GetTimestamp_Call) Run(run func()) *MockErrorEvent_GetTimestamp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockErrorEvent_GetTimestamp_Call) Return(_a0 time.Time) *MockErrorEvent_GetTimestamp_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockErrorEvent_GetTimestamp_Call) RunAndReturn(run func() time.Time) *MockErrorEvent_GetTimestamp_Call {
	_c.Call.Return(run)
	return _c
}

// IsReported provides a mock function with no fields
func (_m *MockErrorEvent) IsReported() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsReported")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockErrorEvent_IsReported_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsReported'
type MockErrorEvent_IsReported_Call struct {
	*mock.Call
}

// IsReported is a helper method to define mock.On call
func (_e *MockErrorEvent_Expecter) IsReported() *MockErrorEvent_IsReported_Call {
	return &MockErrorEvent_IsReported_Call{Call: _e.mock.On("IsReported")}
}

func (_c *MockErrorEvent_IsReported_Call) Run(run func()) *MockErrorEvent_IsReported_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockErrorEvent_IsReported_Call) Return(_a0 bool) *MockErrorEvent_IsReported_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockErrorEvent_IsReported_Call) RunAndReturn(run func() bool) *MockErrorEvent_IsReported_Call {
	_c.Call.Return(run)
	return _c
}

// MarkReported provides a mock function with no fields
func (_m *MockErrorEvent) MarkReported() {
	_m.Called()
}

// MockErrorEvent_MarkReported_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkReported'
type MockErrorEvent_MarkReported_Call struct {
	*mock.Call
}

// MarkReported is a helper method to define mock.On call
func (_e *MockErrorEvent_Expecter) MarkReported() *MockErrorEvent_MarkReported_Call {
	return &MockErrorEvent_MarkReported_Call{Call: _e.mock.On("MarkReported")}
}

func (_c *MockErrorEvent_MarkReported_Call) Run(run func()) *MockErrorEvent_MarkReported_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockErrorEvent_MarkReported_Call) Return() *MockErrorEvent_MarkReported_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorEvent_MarkReported_Call) RunAndReturn(run func()) *MockErrorEvent_MarkReported_Call {
	_c.Run(run)
	return _c
}

// NewMockErrorEvent creates a new instance of MockErrorEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorEvent {
	mock := &MockErrorEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
