// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dbstats "github.com/tphakala/birdnet-go/internal/datastore/dbstats"
)

// MockDBCountersProvider is an autogenerated mock type for the DBCountersProvider type
type MockDBCountersProvider struct {
	mock.Mock
}

type MockDBCountersProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBCountersProvider) EXPECT() *MockDBCountersProvider_Expecter {
	return &MockDBCountersProvider_Expecter{mock: &_m.Mock}
}

// GetDBCounters provides a mock function with no fields
func (_m *MockDBCountersProvider) GetDBCounters() *dbstats.Counters {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDBCounters")
	}

	var r0 *dbstats.Counters
	if rf, ok := ret.Get(0).(func() *dbstats.Counters); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbstats.Counters)
		}
	}

	return r0
}

// MockDBCountersProvider_GetDBCounters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDBCounters'
type MockDBCountersProvider_GetDBCounters_Call struct {
	*mock.Call
}

// GetDBCounters is a helper method to define mock.On call
func (_e *MockDBCountersProvider_Expecter) GetDBCounters() *MockDBCountersProvider_GetDBCounters_Call {
	return &MockDBCountersProvider_GetDBCounters_Call{Call: _e.mock.On("GetDBCounters")}
}

func (_c *MockDBCountersProvider_GetDBCounters_Call) Run(run func()) *MockDBCountersProvider_GetDBCounters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDBCountersProvider_GetDBCounters_Call) Return(_a0 *dbstats.Counters) *MockDBCountersProvider_GetDBCounters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDBCountersProvider_GetDBCounters_Call) RunAndReturn(run func() *dbstats.Counters) *MockDBCountersProvider_GetDBCounters_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBCountersProvider creates a new instance of MockDBCountersProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBCountersProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBCountersProvider {
	mock := &MockDBCountersProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
