// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockSpeciesNameResolver is an autogenerated mock type for the SpeciesNameResolver type
type MockSpeciesNameResolver struct {
	mock.Mock
}

type MockSpeciesNameResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpeciesNameResolver) EXPECT() *MockSpeciesNameResolver_Expecter {
	return &MockSpeciesNameResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: scientificName, locale
func (_m *MockSpeciesNameResolver) Resolve(scientificName string, locale string) string {
	ret := _m.Called(scientificName, locale)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(scientificName, locale)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSpeciesNameResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockSpeciesNameResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - scientificName string
//   - locale string
func (_e *MockSpeciesNameResolver_Expecter) Resolve(scientificName interface{}, locale interface{}) *MockSpeciesNameResolver_Resolve_Call {
	return &MockSpeciesNameResolver_Resolve_Call{Call: _e.mock.On("Resolve", scientificName, locale)}
}

func (_c *MockSpeciesNameResolver_Resolve_Call) Run(run func(scientificName string, locale string)) *MockSpeciesNameResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockSpeciesNameResolver_Resolve_Call) Return(_a0 string) *MockSpeciesNameResolver_Resolve_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSpeciesNameResolver_Resolve_Call) RunAndReturn(run func(string, string) string) *MockSpeciesNameResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSpeciesNameResolver creates a new instance of MockSpeciesNameResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpeciesNameResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpeciesNameResolver {
	mock := &MockSpeciesNameResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
