// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockStoreInterface is an autogenerated mock type for the StoreInterface type
type MockStoreInterface struct {
	mock.Mock
}

type MockStoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoreInterface) EXPECT() *MockStoreInterface_Expecter {
	return &MockStoreInterface_Expecter{mock: &_m.Mock}
}

// GetDBPath provides a mock function with no fields
func (_m *MockStoreInterface) GetDBPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDBPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockStoreInterface_GetDBPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDBPath'
type MockStoreInterface_GetDBPath_Call struct {
	*mock.Call
}

// GetDBPath is a helper method to define mock.On call
func (_e *MockStoreInterface_Expecter) GetDBPath() *MockStoreInterface_GetDBPath_Call {
	return &MockStoreInterface_GetDBPath_Call{Call: _e.mock.On("GetDBPath")}
}

func (_c *MockStoreInterface_GetDBPath_Call) Run(run func()) *MockStoreInterface_GetDBPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStoreInterface_GetDBPath_Call) Return(_a0 string) *MockStoreInterface_GetDBPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStoreInterface_GetDBPath_Call) RunAndReturn(run func() string) *MockStoreInterface_GetDBPath_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStoreInterface creates a new instance of MockStoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreInterface {
	mock := &MockStoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
