// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	datastore "github.com/tphakala/birdnet-go/internal/datastore"
)

// MockDatabaseInspector is an autogenerated mock type for the DatabaseInspector type
type MockDatabaseInspector struct {
	mock.Mock
}

type MockDatabaseInspector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabaseInspector) EXPECT() *MockDatabaseInspector_Expecter {
	return &MockDatabaseInspector_Expecter{mock: &_m.Mock}
}

// GetDetectionRate24h provides a mock function with no fields
func (_m *MockDatabaseInspector) GetDetectionRate24h() ([]datastore.HourlyCount, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDetectionRate24h")
	}

	var r0 []datastore.HourlyCount
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]datastore.HourlyCount, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []datastore.HourlyCount); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datastore.HourlyCount)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseInspector_GetDetectionRate24h_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetectionRate24h'
type MockDatabaseInspector_GetDetectionRate24h_Call struct {
	*mock.Call
}

// GetDetectionRate24h is a helper method to define mock.On call
func (_e *MockDatabaseInspector_Expecter) GetDetectionRate24h() *MockDatabaseInspector_GetDetectionRate24h_Call {
	return &MockDatabaseInspector_GetDetectionRate24h_Call{Call: _e.mock.On("GetDetectionRate24h")}
}

func (_c *MockDatabaseInspector_GetDetectionRate24h_Call) Run(run func()) *MockDatabaseInspector_GetDetectionRate24h_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabaseInspector_GetDetectionRate24h_Call) Return(_a0 []datastore.HourlyCount, _a1 error) *MockDatabaseInspector_GetDetectionRate24h_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseInspector_GetDetectionRate24h_Call) RunAndReturn(run func() ([]datastore.HourlyCount, error)) *MockDatabaseInspector_GetDetectionRate24h_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetectionRateDaily provides a mock function with given fields: days
func (_m *MockDatabaseInspector) GetDetectionRateDaily(days int) ([]datastore.DailyCount, error) {
	ret := _m.Called(days)

	if len(ret) == 0 {
		panic("no return value specified for GetDetectionRateDaily")
	}

	var r0 []datastore.DailyCount
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]datastore.DailyCount, error)); ok {
		return rf(days)
	}
	if rf, ok := ret.Get(0).(func(int) []datastore.DailyCount); ok {
		r0 = rf(days)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datastore.DailyCount)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(days)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseInspector_GetDetectionRateDaily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetectionRateDaily'
type MockDatabaseInspector_GetDetectionRateDaily_Call struct {
	*mock.Call
}

// GetDetectionRateDaily is a helper method to define mock.On call
//   - days int
func (_e *MockDatabaseInspector_Expecter) GetDetectionRateDaily(days interface{}) *MockDatabaseInspector_GetDetectionRateDaily_Call {
	return &MockDatabaseInspector_GetDetectionRateDaily_Call{Call: _e.mock.On("GetDetectionRateDaily", days)}
}

func (_c *MockDatabaseInspector_GetDetectionRateDaily_Call) Run(run func(days int)) *MockDatabaseInspector_GetDetectionRateDaily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockDatabaseInspector_GetDetectionRateDaily_Call) Return(_a0 []datastore.DailyCount, _a1 error) *MockDatabaseInspector_GetDetectionRateDaily_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseInspector_GetDetectionRateDaily_Call) RunAndReturn(run func(int) ([]datastore.DailyCount, error)) *MockDatabaseInspector_GetDetectionRateDaily_Call {
	_c.Call.Return(run)
	return _c
}

// GetEngineDetails provides a mock function with no fields
func (_m *MockDatabaseInspector) GetEngineDetails() (datastore.EngineDetails, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEngineDetails")
	}

	var r0 datastore.EngineDetails
	var r1 error
	if rf, ok := ret.Get(0).(func() (datastore.EngineDetails, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() datastore.EngineDetails); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(datastore.EngineDetails)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseInspector_GetEngineDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEngineDetails'
type MockDatabaseInspector_GetEngineDetails_Call struct {
	*mock.Call
}

// GetEngineDetails is a helper method to define mock.On call
func (_e *MockDatabaseInspector_Expecter) GetEngineDetails() *MockDatabaseInspector_GetEngineDetails_Call {
	return &MockDatabaseInspector_GetEngineDetails_Call{Call: _e.mock.On("GetEngineDetails")}
}

func (_c *MockDatabaseInspector_GetEngineDetails_Call) Run(run func()) *MockDatabaseInspector_GetEngineDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabaseInspector_GetEngineDetails_Call) Return(_a0 datastore.EngineDetails, _a1 error) *MockDatabaseInspector_GetEngineDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseInspector_GetEngineDetails_Call) RunAndReturn(run func() (datastore.EngineDetails, error)) *MockDatabaseInspector_GetEngineDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetTableStats provides a mock function with no fields
func (_m *MockDatabaseInspector) GetTableStats() ([]datastore.TableStats, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTableStats")
	}

	var r0 []datastore.TableStats
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]datastore.TableStats, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []datastore.TableStats); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datastore.TableStats)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseInspector_GetTableStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTableStats'
type MockDatabaseInspector_GetTableStats_Call struct {
	*mock.Call
}

// GetTableStats is a helper method to define mock.On call
func (_e *MockDatabaseInspector_Expecter) GetTableStats() *MockDatabaseInspector_GetTableStats_Call {
	return &MockDatabaseInspector_GetTableStats_Call{Call: _e.mock.On("GetTableStats")}
}

func (_c *MockDatabaseInspector_GetTableStats_Call) Run(run func()) *MockDatabaseInspector_GetTableStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabaseInspector_GetTableStats_Call) Return(_a0 []datastore.TableStats, _a1 error) *MockDatabaseInspector_GetTableStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseInspector_GetTableStats_Call) RunAndReturn(run func() ([]datastore.TableStats, error)) *MockDatabaseInspector_GetTableStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDatabaseInspector creates a new instance of MockDatabaseInspector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabaseInspector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabaseInspector {
	mock := &MockDatabaseInspector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
