// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	notification "github.com/tphakala/birdnet-go/internal/notification"
)

// MockNoticeService is an autogenerated mock type for the NoticeService type
type MockNoticeService struct {
	mock.Mock
}

type MockNoticeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoticeService) EXPECT() *MockNoticeService_Expecter {
	return &MockNoticeService_Expecter{mock: &_m.Mock}
}

// CreateWithMetadata provides a mock function with given fields: notif
func (_m *MockNoticeService) CreateWithMetadata(notif *notification.Notification) error {
	ret := _m.Called(notif)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithMetadata")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*notification.Notification) error); ok {
		r0 = rf(notif)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNoticeService_CreateWithMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithMetadata'
type MockNoticeService_CreateWithMetadata_Call struct {
	*mock.Call
}

// CreateWithMetadata is a helper method to define mock.On call
//   - notif *notification.Notification
func (_e *MockNoticeService_Expecter) CreateWithMetadata(notif interface{}) *MockNoticeService_CreateWithMetadata_Call {
	return &MockNoticeService_CreateWithMetadata_Call{Call: _e.mock.On("CreateWithMetadata", notif)}
}

func (_c *MockNoticeService_CreateWithMetadata_Call) Run(run func(notif *notification.Notification)) *MockNoticeService_CreateWithMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*notification.Notification))
	})
	return _c
}

func (_c *MockNoticeService_CreateWithMetadata_Call) Return(_a0 error) *MockNoticeService_CreateWithMetadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNoticeService_CreateWithMetadata_Call) RunAndReturn(run func(*notification.Notification) error) *MockNoticeService_CreateWithMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockNoticeService) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNoticeService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNoticeService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockNoticeService_Expecter) Delete(id interface{}) *MockNoticeService_Delete_Call {
	return &MockNoticeService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockNoticeService_Delete_Call) Run(run func(id string)) *MockNoticeService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockNoticeService_Delete_Call) Return(_a0 error) *MockNoticeService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNoticeService_Delete_Call) RunAndReturn(run func(string) error) *MockNoticeService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNoticeService creates a new instance of MockNoticeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoticeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoticeService {
	mock := &MockNoticeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
