// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	notification "github.com/tphakala/birdnet-go/internal/notification"
)

// MockNotificationStore is an autogenerated mock type for the NotificationStore type
type MockNotificationStore struct {
	mock.Mock
}

type MockNotificationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationStore) EXPECT() *MockNotificationStore_Expecter {
	return &MockNotificationStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: id
func (_m *MockNotificationStore) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockNotificationStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockNotificationStore_Expecter) Delete(id interface{}) *MockNotificationStore_Delete_Call {
	return &MockNotificationStore_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockNotificationStore_Delete_Call) Run(run func(id string)) *MockNotificationStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockNotificationStore_Delete_Call) Return(_a0 error) *MockNotificationStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationStore_Delete_Call) RunAndReturn(run func(string) error) *MockNotificationStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function with no fields
func (_m *MockNotificationStore) DeleteExpired() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationStore_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type MockNotificationStore_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
func (_e *MockNotificationStore_Expecter) DeleteExpired() *MockNotificationStore_DeleteExpired_Call {
	return &MockNotificationStore_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired")}
}

func (_c *MockNotificationStore_DeleteExpired_Call) Run(run func()) *MockNotificationStore_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotificationStore_DeleteExpired_Call) Return(_a0 error) *MockNotificationStore_DeleteExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationStore_DeleteExpired_Call) RunAndReturn(run func() error) *MockNotificationStore_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *MockNotificationStore) Get(id string) (*notification.Notification, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *notification.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*notification.Notification, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *notification.Notification); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notification.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockNotificationStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MockNotificationStore_Expecter) Get(id interface{}) *MockNotificationStore_Get_Call {
	return &MockNotificationStore_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockNotificationStore_Get_Call) Run(run func(id string)) *MockNotificationStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockNotificationStore_Get_Call) Return(_a0 *notification.Notification, _a1 error) *MockNotificationStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationStore_Get_Call) RunAndReturn(run func(string) (*notification.Notification, error)) *MockNotificationStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnreadCount provides a mock function with no fields
func (_m *MockNotificationStore) GetUnreadCount() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUnreadCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationStore_GetUnreadCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnreadCount'
type MockNotificationStore_GetUnreadCount_Call struct {
	*mock.Call
}

// GetUnreadCount is a helper method to define mock.On call
func (_e *MockNotificationStore_Expecter) GetUnreadCount() *MockNotificationStore_GetUnreadCount_Call {
	return &MockNotificationStore_GetUnreadCount_Call{Call: _e.mock.On("GetUnreadCount")}
}

func (_c *MockNotificationStore_GetUnreadCount_Call) Run(run func()) *MockNotificationStore_GetUnreadCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotificationStore_GetUnreadCount_Call) Return(_a0 int, _a1 error) *MockNotificationStore_GetUnreadCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationStore_GetUnreadCount_Call) RunAndReturn(run func() (int, error)) *MockNotificationStore_GetUnreadCount_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: filter
func (_m *MockNotificationStore) List(filter *notification.FilterOptions) ([]*notification.Notification, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*notification.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(*notification.FilterOptions) ([]*notification.Notification, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(*notification.FilterOptions) []*notification.Notification); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*notification.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(*notification.FilterOptions) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockNotificationStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - filter *notification.FilterOptions
func (_e *MockNotificationStore_Expecter) List(filter interface{}) *MockNotificationStore_List_Call {
	return &MockNotificationStore_List_Call{Call: _e.mock.On("List", filter)}
}

func (_c *MockNotificationStore_List_Call) Run(run func(filter *notification.FilterOptions)) *MockNotificationStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*notification.FilterOptions))
	})
	return _c
}

func (_c *MockNotificationStore_List_Call) Return(_a0 []*notification.Notification, _a1 error) *MockNotificationStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationStore_List_Call) RunAndReturn(run func(*notification.FilterOptions) ([]*notification.Notification, error)) *MockNotificationStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: _a0
func (_m *MockNotificationStore) Save(_a0 *notification.Notification) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*notification.Notification) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockNotificationStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - _a0 *notification.Notification
func (_e *MockNotificationStore_Expecter) Save(_a0 interface{}) *MockNotificationStore_Save_Call {
	return &MockNotificationStore_Save_Call{Call: _e.mock.On("Save", _a0)}
}

func (_c *MockNotificationStore_Save_Call) Run(run func(_a0 *notification.Notification)) *MockNotificationStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*notification.Notification))
	})
	return _c
}

func (_c *MockNotificationStore_Save_Call) Return(_a0 error) *MockNotificationStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationStore_Save_Call) RunAndReturn(run func(*notification.Notification) error) *MockNotificationStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0
func (_m *MockNotificationStore) Update(_a0 *notification.Notification) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*notification.Notification) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockNotificationStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 *notification.Notification
func (_e *MockNotificationStore_Expecter) Update(_a0 interface{}) *MockNotificationStore_Update_Call {
	return &MockNotificationStore_Update_Call{Call: _e.mock.On("Update", _a0)}
}

func (_c *MockNotificationStore_Update_Call) Run(run func(_a0 *notification.Notification)) *MockNotificationStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*notification.Notification))
	})
	return _c
}

func (_c *MockNotificationStore_Update_Call) Return(_a0 error) *MockNotificationStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationStore_Update_Call) RunAndReturn(run func(*notification.Notification) error) *MockNotificationStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationStore creates a new instance of MockNotificationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationStore {
	mock := &MockNotificationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
