// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	notification "github.com/tphakala/birdnet-go/internal/notification"
)

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// GetName provides a mock function with no fields
func (_m *MockProvider) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockProvider_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockProvider_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockProvider_Expecter) GetName() *MockProvider_GetName_Call {
	return &MockProvider_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockProvider_GetName_Call) Run(run func()) *MockProvider_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_GetName_Call) Return(_a0 string) *MockProvider_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvider_GetName_Call) RunAndReturn(run func() string) *MockProvider_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// IsEnabled provides a mock function with no fields
func (_m *MockProvider) IsEnabled() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockProvider_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockProvider_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
func (_e *MockProvider_Expecter) IsEnabled() *MockProvider_IsEnabled_Call {
	return &MockProvider_IsEnabled_Call{Call: _e.mock.On("IsEnabled")}
}

func (_c *MockProvider_IsEnabled_Call) Run(run func()) *MockProvider_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_IsEnabled_Call) Return(_a0 bool) *MockProvider_IsEnabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvider_IsEnabled_Call) RunAndReturn(run func() bool) *MockProvider_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: ctx, n
func (_m *MockProvider) Send(ctx context.Context, n *notification.Notification) error {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *notification.Notification) error); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProvider_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockProvider_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - n *notification.Notification
func (_e *MockProvider_Expecter) Send(ctx interface{}, n interface{}) *MockProvider_Send_Call {
	return &MockProvider_Send_Call{Call: _e.mock.On("Send", ctx, n)}
}

func (_c *MockProvider_Send_Call) Run(run func(ctx context.Context, n *notification.Notification)) *MockProvider_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*notification.Notification))
	})
	return _c
}

func (_c *MockProvider_Send_Call) Return(_a0 error) *MockProvider_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvider_Send_Call) RunAndReturn(run func(context.Context, *notification.Notification) error) *MockProvider_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsType provides a mock function with given fields: notifType
func (_m *MockProvider) SupportsType(notifType notification.Type) bool {
	ret := _m.Called(notifType)

	if len(ret) == 0 {
		panic("no return value specified for SupportsType")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(notification.Type) bool); ok {
		r0 = rf(notifType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockProvider_SupportsType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsType'
type MockProvider_SupportsType_Call struct {
	*mock.Call
}

// SupportsType is a helper method to define mock.On call
//   - notifType notification.Type
func (_e *MockProvider_Expecter) SupportsType(notifType interface{}) *MockProvider_SupportsType_Call {
	return &MockProvider_SupportsType_Call{Call: _e.mock.On("SupportsType", notifType)}
}

func (_c *MockProvider_SupportsType_Call) Run(run func(notifType notification.Type)) *MockProvider_SupportsType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notification.Type))
	})
	return _c
}

func (_c *MockProvider_SupportsType_Call) Return(_a0 bool) *MockProvider_SupportsType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvider_SupportsType_Call) RunAndReturn(run func(notification.Type) bool) *MockProvider_SupportsType_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateConfig provides a mock function with no fields
func (_m *MockProvider) ValidateConfig() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ValidateConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProvider_ValidateConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateConfig'
type MockProvider_ValidateConfig_Call struct {
	*mock.Call
}

// ValidateConfig is a helper method to define mock.On call
func (_e *MockProvider_Expecter) ValidateConfig() *MockProvider_ValidateConfig_Call {
	return &MockProvider_ValidateConfig_Call{Call: _e.mock.On("ValidateConfig")}
}

func (_c *MockProvider_ValidateConfig_Call) Run(run func()) *MockProvider_ValidateConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_ValidateConfig_Call) Return(_a0 error) *MockProvider_ValidateConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvider_ValidateConfig_Call) RunAndReturn(run func() error) *MockProvider_ValidateConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
