// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockTelemetryReporter is an autogenerated mock type for the TelemetryReporter type
type MockTelemetryReporter struct {
	mock.Mock
}

type MockTelemetryReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelemetryReporter) EXPECT() *MockTelemetryReporter_Expecter {
	return &MockTelemetryReporter_Expecter{mock: &_m.Mock}
}

// CaptureError provides a mock function with given fields: err, component
func (_m *MockTelemetryReporter) CaptureError(err error, component string) {
	_m.Called(err, component)
}

// MockTelemetryReporter_CaptureError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CaptureError'
type MockTelemetryReporter_CaptureError_Call struct {
	*mock.Call
}

// CaptureError is a helper method to define mock.On call
//   - err error
//   - component string
func (_e *MockTelemetryReporter_Expecter) CaptureError(err interface{}, component interface{}) *MockTelemetryReporter_CaptureError_Call {
	return &MockTelemetryReporter_CaptureError_Call{Call: _e.mock.On("CaptureError", err, component)}
}

func (_c *MockTelemetryReporter_CaptureError_Call) Run(run func(err error, component string)) *MockTelemetryReporter_CaptureError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error), args[1].(string))
	})
	return _c
}

func (_c *MockTelemetryReporter_CaptureError_Call) Return() *MockTelemetryReporter_CaptureError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTelemetryReporter_CaptureError_Call) RunAndReturn(run func(error, string)) *MockTelemetryReporter_CaptureError_Call {
	_c.Run(run)
	return _c
}

// CaptureEvent provides a mock function with given fields: message, level, tags, contexts
func (_m *MockTelemetryReporter) CaptureEvent(message string, level string, tags map[string]string, contexts map[string]interface{}) {
	_m.Called(message, level, tags, contexts)
}

// MockTelemetryReporter_CaptureEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CaptureEvent'
type MockTelemetryReporter_CaptureEvent_Call struct {
	*mock.Call
}

// CaptureEvent is a helper method to define mock.On call
//   - message string
//   - level string
//   - tags map[string]string
//   - contexts map[string]interface{}
func (_e *MockTelemetryReporter_Expecter) CaptureEvent(message interface{}, level interface{}, tags interface{}, contexts interface{}) *MockTelemetryReporter_CaptureEvent_Call {
	return &MockTelemetryReporter_CaptureEvent_Call{Call: _e.mock.On("CaptureEvent", message, level, tags, contexts)}
}

func (_c *MockTelemetryReporter_CaptureEvent_Call) Run(run func(message string, level string, tags map[string]string, contexts map[string]interface{})) *MockTelemetryReporter_CaptureEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(map[string]string), args[3].(map[string]interface{}))
	})
	return _c
}

func (_c *MockTelemetryReporter_CaptureEvent_Call) Return() *MockTelemetryReporter_CaptureEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTelemetryReporter_CaptureEvent_Call) RunAndReturn(run func(string, string, map[string]string, map[string]interface{})) *MockTelemetryReporter_CaptureEvent_Call {
	_c.Run(run)
	return _c
}

// IsEnabled provides a mock function with no fields
func (_m *MockTelemetryReporter) IsEnabled() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockTelemetryReporter_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockTelemetryReporter_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
func (_e *MockTelemetryReporter_Expecter) IsEnabled() *MockTelemetryReporter_IsEnabled_Call {
	return &MockTelemetryReporter_IsEnabled_Call{Call: _e.mock.On("IsEnabled")}
}

func (_c *MockTelemetryReporter_IsEnabled_Call) Run(run func()) *MockTelemetryReporter_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTelemetryReporter_IsEnabled_Call) Return(_a0 bool) *MockTelemetryReporter_IsEnabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTelemetryReporter_IsEnabled_Call) RunAndReturn(run func() bool) *MockTelemetryReporter_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTelemetryReporter creates a new instance of MockTelemetryReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelemetryReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelemetryReporter {
	mock := &MockTelemetryReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
